.codespell:
        stage: test
        script:
                - mkdir codespell
                - codespell | tee ./codespell/codespell.log
        artifacts:
                when: on_failure
                paths:
                        - ./codespell/codespell.log
