.gitlint:
  before_script:
    - git fetch origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}:refs/remotes/origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
  script:
    - base=origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    - merge_base=$(git merge-base --fork-point ${base} HEAD)
    - gitlint --commits ${merge_base}..${head}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
