name: fastci
on:
  pull_request

jobs:
  check-gitlint:
    uses: ./.github/workflows/gitlint.yml
  check-codespell:
    uses: ./.github/workflows/codespell.yml
  check-cmake-lint:
    uses: ./.github/workflows/cmake-lint.yml
  check-clang-scan:
    uses: ./.github/workflows/clang-scan.yml
  check-clang:
    uses: ./.github/workflows/compile.yml
    with:
      compiler: clang
  check-gcc:
    uses: ./.github/workflows/compile.yml
    with:
      compiler: gcc
  fastci:
    runs-on: [self-hosted, Linux]
    needs:
    - check-gitlint
    - check-codespell
    - check-cmake-lint
    - check-clang-scan
    - check-clang
    - check-gcc
    steps:
    - name: fastci
      run: |
        echo "okay"
