name: ubuntu-compile
on:
   workflow_call:
     inputs:
       compiler:
         description: 'Compiler'
         default: 'gcc'
         required: false
         type: string

jobs:
  clang-compile:
    runs-on: [UbuntuJer]
    env:
      BUILDDIR: /tmp/build
    name: Compile with ${{ inputs.compiler }}
    strategy:
      matrix:
        container:
        - "lms-ubuntu:18.04"
        - "lms-ubuntu:20.04"

    container:
      image: ger-registry.caas.intel.com/sfip-sw/${{ matrix.container }}
      options: --user 18411
    steps:
      - name: Checkout the PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Create build dir
        run: mkdir ${BUILDDIR}/

      - name: Run on ${{ matrix.container }} cmake compilation with ${{ inputs.compiler }}
        shell: bash
        run: |
          CMAKE_BUILD_DIR=${BUILDDIR}/cmake
          CMAKE_ARGS="-DCMAKE_C_COMPILER=${{ inputs.compiler }} -DENABLE_TESTS:BOOL=ON"
          cmake --version
          mkdir -p ${CMAKE_BUILD_DIR}
          pushd ${CMAKE_BUILD_DIR}
          cmake ${GITHUB_WORKSPACE} ${CMAKE_ARGS}
          popd
          make -C ${CMAKE_BUILD_DIR} -j$(nproc) package

      - name: Run on ${{ matrix.container }} meson compilation with ${{ inputs.compiler }}
        run: |
          CC=${{ inputs.compiler }} meson setup $BUILDDIR/meson/
          meson configure -Dbuildtype=debug $BUILDDIR/meson
          ninja -v -C $BUILDDIR/meson
          meson configure -Dbuildtype=release ${BUILDDIR}/meson
          ninja -v -C ${BUILDDIR}/meson
